### ISSUE TITLE
Implement DeleteItem API

### ISSUE THREAD

**Issue by li-boxuan** [li-boxuan/stargate#21]
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DeleteItem.html

This needs to parse ConditionExpression. An example of how to parse expressions can be found in https://github.com/li-boxuan/stargate/pull/18

**Comment by Blickwinkel1107** [comment]
Finished

**Comment by li-boxuan** [comment]
@Blickwinkel1107 Can you please migrate the changes to https://github.com/li-boxuan/cassandra-dynamoDB-adapter repo?

**Comment by Blickwinkel1107** [comment]
No problem. Let me do that
